In [1]:
#This section is importing all libraries & data used for the project

#importing all necessary libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import scipy.stats as stats

#importing the data file
data = pd.read_csv("./DataFiles/CreditCard_train.csv", header=1)
#displaying the first 10 rows of the data
data.head(10)

,ID,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_0,PAY_2,PAY_3,PAY_4,...,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,default payment next month
0,1,20000,2,2,1,24,2,2,-1,-1,...,0,0,0,0,689,0,0,0,0,1
1,2,120000,2,2,2,26,-1,2,0,0,...,3272,3455,3261,0,1000,1000,1000,0,2000,1
2,3,90000,2,2,2,34,0,0,0,0,...,14331,14948,15549,1518,1500,1000,1000,1000,5000,0
3,4,50000,2,2,1,37,0,0,0,0,...,28314,28959,29547,2000,2019,1200,1100,1069,1000,0
4,5,50000,1,2,1,57,-1,0,-1,0,...,20940,19146,19131,2000,36681,10000,9000,689,679,0
5,6,50000,1,1,2,37,0,0,0,0,...,19394,19619,20024,2500,1815,657,1000,1000,800,0
6,7,500000,1,1,2,29,0,0,0,0,...,542653,483003,473944,55000,40000,38000,20239,13750,13770,0
7,8,100000,2,2,2,23,0,-1,-1,0,...,221,-159,567,380,601,0,581,1687,1542,0
8,9,140000,2,3,1,28,0,0,2,0,...,12211,11793,3719,3329,0,432,1000,1000,1000,0
9,10,20000,1,3,2,35,-2,-2,-2,-2,...,0,13007,13912,0,0,0,13007,1122,0,0

In [2]:
categories = ['SEX', 'EDUCATION', 'MARRIAGE', 'PAY_0', 'PAY_2', 'PAY_3', 'PAY_4', 'PAY_5', 'PAY_6']
for element in categories:
    data[element] = data[element].astype('category')
    
for element in categories:
    data = pd.concat((data, pd.get_dummies(data[element], prefix=[element])), axis=1)
    
data

,ID,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_0,PAY_2,PAY_3,PAY_4,...,['PAY_6']_-2,['PAY_6']_-1,['PAY_6']_0,['PAY_6']_2,['PAY_6']_3,['PAY_6']_4,['PAY_6']_5,['PAY_6']_6,['PAY_6']_7,['PAY_6']_8
0,1,20000,2,2,1,24,2,2,-1,-1,...,1,0,0,0,0,0,0,0,0,0
1,2,120000,2,2,2,26,-1,2,0,0,...,0,0,0,1,0,0,0,0,0,0
2,3,90000,2,2,2,34,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
3,4,50000,2,2,1,37,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
4,5,50000,1,2,1,57,-1,0,-1,0,...,0,0,1,0,0,0,0,0,0,0
5,6,50000,1,1,2,37,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
6,7,500000,1,1,2,29,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
7,8,100000,2,2,2,23,0,-1,-1,0,...,0,1,0,0,0,0,0,0,0,0
8,9,140000,2,3,1,28,0,0,2,0,...,0,0,1,0,0,0,0,0,0,0
9,10,20000,1,3,2,35,-2,-2,-2,-2,...,0,1,0,0,0,0,0,0,0,0
10,11,200000,2,3,2,34,0,0,2,0,...,0,1,0,0,0,0,0,0,0,0
11,12,260000,2,1,2,51,-1,-1,-1,-1,...,0,0,0,1,0,0,0,0,0,0
12,13,630000,2,2,2,41,-1,0,-1,-1,...,0,1,0,0,0,0,0,0,0,0
13,14,70000,1,2,2,30,1,2,2,0,...,0,0,0,1,0,0,0,0,0,0
14,15,250000,1,1,2,29,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
15,16,50000,2,3,3,23,1,2,0,0,...,0,0,1,0,0,0,0,0,0,0
16,17,20000,1,1,2,24,0,0,2,2,...,0,0,0,1,0,0,0,0,0,0
17,18,320000,1,1,1,49,0,0,0,-1,...,0,1,0,0,0,0,0,0,0,0
18,19,360000,2,1,1,49,1,-2,-2,-2,...,1,0,0,0,0,0,0,0,0,0
19,20,180000,2,1,2,29,1,-2,-2,-2,...,1,0,0,0,0,0,0,0,0,0
20,21,130000,2,3,2,39,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
21,22,120000,2,2,1,39,-1,-1,-1,-1,...,0,1,0,0,0,0,0,0,0,0
22,23,70000,2,2,2,26,2,0,0,2,...,0,0,0,1,0,0,0,0,0,0
23,24,450000,2,1,1,40,-2,-2,-2,-2,...,1,0,0,0,0,0,0,0,0,0
24,25,90000,1,1,2,23,0,0,0,-1,...,0,0,1,0,0,0,0,0,0,0
25,26,50000,1,3,2,23,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
26,27,60000,1,1,2,27,1,-2,-1,-1,...,0,1,0,0,0,0,0,0,0,0
27,28,50000,2,3,2,30,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
28,29,50000,2,3,1,47,-1,-1,-1,-1,...,0,1,0,0,0,0,0,0,0,0
29,30,50000,1,1,2,26,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23970,23971,50000,1,1,2,27,0,0,2,0,...,0,0,0,1,0,0,0,0,0,0
23971,23972,50000,1,2,2,25,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
23972,23973,10000,1,2,2,26,1,-1,0,0,...,0,0,1,0,0,0,0,0,0,0
23973,23974,50000,1,1,2,25,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
23974,23975,50000,1,2,2,26,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
23975,23976,20000,1,1,2,25,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
23976,23977,200000,1,1,2,26,-2,-2,-2,-2,...,1,0,0,0,0,0,0,0,0,0
23977,23978,40000,1,1,2,26,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
23978,23979,30000,1,2,2,23,0,0,2,2,...,0,0,1,0,0,0,0,0,0,0
23979,23980,20000,1,2,2,23,2,0,0,2,...,0,0,1,0,0,0,0,0,0,0
23980,23981,50000,1,2,2,23,0,0,0,-1,...,0,0,1,0,0,0,0,0,0,0
23981,23982,20000,1,3,2,24,-1,2,-1,-1,...,0,1,0,0,0,0,0,0,0,0
23982,23983,130000,1,2,2,25,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
23983,23984,160000,1,2,2,25,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
23984,23985,110000,1,2,2,25,0,-1,0,0,...,0,1,0,0,0,0,0,0,0,0
23985,23986,50000,1,2,2,37,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
23986,23987,50000,1,2,2,25,0,0,4,3,...,0,0,0,1,0,0,0,0,0,0
23987,23988,240000,1,2,2,26,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
23988,23989,20000,1,2,2,27,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
23989,23990,500000,1,3,2,30,-1,0,0,0,...,0,1,0,0,0,0,0,0,0,0
23990,23991,60000,1,2,2,26,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
23991,23992,50000,1,3,2,25,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
23992,23993,50000,1,2,2,24,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
23993,23994,20000,1,2,2,25,-1,-1,-1,-1,...,0,0,1,0,0,0,0,0,0,0
23994,23995,30000,1,2,2,25,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
23995,23996,80000,1,2,1,25,1,2,2,0,...,0,0,1,0,0,0,0,0,0,0
23996,23997,20000,1,2,1,25,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
23997,23998,10000,1,2,2,26,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
23998,23999,20000,1,5,2,26,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
23999,24000,100000,1,1,2,26,0,-1,0,0,...,0,0,1,0,0,0,0,0,0,0

In [3]:
#displaying the columns of the data file
print(list(data.columns))
data

['ID', 'LIMIT_BAL', 'SEX', 'EDUCATION', 'MARRIAGE', 'AGE', 'PAY_0', 'PAY_2', 'PAY_3', 'PAY_4', 'PAY_5', 'PAY_6', 'BILL_AMT1', 'BILL_AMT2', 'BILL_AMT3', 'BILL_AMT4', 'BILL_AMT5', 'BILL_AMT6', 'PAY_AMT1', 'PAY_AMT2', 'PAY_AMT3', 'PAY_AMT4', 'PAY_AMT5', 'PAY_AMT6', 'default payment next month', "['SEX']_1", "['SEX']_2", "['EDUCATION']_0", "['EDUCATION']_1", "['EDUCATION']_2", "['EDUCATION']_3", "['EDUCATION']_4", "['EDUCATION']_5", "['EDUCATION']_6", "['MARRIAGE']_0", "['MARRIAGE']_1", "['MARRIAGE']_2", "['MARRIAGE']_3", "['PAY_0']_-2", "['PAY_0']_-1", "['PAY_0']_0", "['PAY_0']_1", "['PAY_0']_2", "['PAY_0']_3", "['PAY_0']_4", "['PAY_0']_5", "['PAY_0']_6", "['PAY_0']_7", "['PAY_0']_8", "['PAY_2']_-2", "['PAY_2']_-1", "['PAY_2']_0", "['PAY_2']_1", "['PAY_2']_2", "['PAY_2']_3", "['PAY_2']_4", "['PAY_2']_5", "['PAY_2']_6", "['PAY_2']_7", "['PAY_2']_8", "['PAY_3']_-2", "['PAY_3']_-1", "['PAY_3']_0", "['PAY_3']_1", "['PAY_3']_2", "['PAY_3']_3", "['PAY_3']_4", "['PAY_3']_5", "['PAY_3']_6", "['PAY_3']_7", "['PAY_3']_8", "['PAY_4']_-2", "['PAY_4']_-1", "['PAY_4']_0", "['PAY_4']_1", "['PAY_4']_2", "['PAY_4']_3", "['PAY_4']_4", "['PAY_4']_5", "['PAY_4']_6", "['PAY_4']_7", "['PAY_4']_8", "['PAY_5']_-2", "['PAY_5']_-1", "['PAY_5']_0", "['PAY_5']_2", "['PAY_5']_3", "['PAY_5']_4", "['PAY_5']_5", "['PAY_5']_6", "['PAY_5']_7", "['PAY_5']_8", "['PAY_6']_-2", "['PAY_6']_-1", "['PAY_6']_0", "['PAY_6']_2", "['PAY_6']_3", "['PAY_6']_4", "['PAY_6']_5", "['PAY_6']_6", "['PAY_6']_7", "['PAY_6']_8"]

,ID,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_0,PAY_2,PAY_3,PAY_4,...,['PAY_6']_-2,['PAY_6']_-1,['PAY_6']_0,['PAY_6']_2,['PAY_6']_3,['PAY_6']_4,['PAY_6']_5,['PAY_6']_6,['PAY_6']_7,['PAY_6']_8
0,1,20000,2,2,1,24,2,2,-1,-1,...,1,0,0,0,0,0,0,0,0,0
1,2,120000,2,2,2,26,-1,2,0,0,...,0,0,0,1,0,0,0,0,0,0
2,3,90000,2,2,2,34,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
3,4,50000,2,2,1,37,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
4,5,50000,1,2,1,57,-1,0,-1,0,...,0,0,1,0,0,0,0,0,0,0
5,6,50000,1,1,2,37,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
6,7,500000,1,1,2,29,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
7,8,100000,2,2,2,23,0,-1,-1,0,...,0,1,0,0,0,0,0,0,0,0
8,9,140000,2,3,1,28,0,0,2,0,...,0,0,1,0,0,0,0,0,0,0
9,10,20000,1,3,2,35,-2,-2,-2,-2,...,0,1,0,0,0,0,0,0,0,0
10,11,200000,2,3,2,34,0,0,2,0,...,0,1,0,0,0,0,0,0,0,0
11,12,260000,2,1,2,51,-1,-1,-1,-1,...,0,0,0,1,0,0,0,0,0,0
12,13,630000,2,2,2,41,-1,0,-1,-1,...,0,1,0,0,0,0,0,0,0,0
13,14,70000,1,2,2,30,1,2,2,0,...,0,0,0,1,0,0,0,0,0,0
14,15,250000,1,1,2,29,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
15,16,50000,2,3,3,23,1,2,0,0,...,0,0,1,0,0,0,0,0,0,0
16,17,20000,1,1,2,24,0,0,2,2,...,0,0,0,1,0,0,0,0,0,0
17,18,320000,1,1,1,49,0,0,0,-1,...,0,1,0,0,0,0,0,0,0,0
18,19,360000,2,1,1,49,1,-2,-2,-2,...,1,0,0,0,0,0,0,0,0,0
19,20,180000,2,1,2,29,1,-2,-2,-2,...,1,0,0,0,0,0,0,0,0,0
20,21,130000,2,3,2,39,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
21,22,120000,2,2,1,39,-1,-1,-1,-1,...,0,1,0,0,0,0,0,0,0,0
22,23,70000,2,2,2,26,2,0,0,2,...,0,0,0,1,0,0,0,0,0,0
23,24,450000,2,1,1,40,-2,-2,-2,-2,...,1,0,0,0,0,0,0,0,0,0
24,25,90000,1,1,2,23,0,0,0,-1,...,0,0,1,0,0,0,0,0,0,0
25,26,50000,1,3,2,23,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
26,27,60000,1,1,2,27,1,-2,-1,-1,...,0,1,0,0,0,0,0,0,0,0
27,28,50000,2,3,2,30,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
28,29,50000,2,3,1,47,-1,-1,-1,-1,...,0,1,0,0,0,0,0,0,0,0
29,30,50000,1,1,2,26,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23970,23971,50000,1,1,2,27,0,0,2,0,...,0,0,0,1,0,0,0,0,0,0
23971,23972,50000,1,2,2,25,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
23972,23973,10000,1,2,2,26,1,-1,0,0,...,0,0,1,0,0,0,0,0,0,0
23973,23974,50000,1,1,2,25,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
23974,23975,50000,1,2,2,26,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
23975,23976,20000,1,1,2,25,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
23976,23977,200000,1,1,2,26,-2,-2,-2,-2,...,1,0,0,0,0,0,0,0,0,0
23977,23978,40000,1,1,2,26,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
23978,23979,30000,1,2,2,23,0,0,2,2,...,0,0,1,0,0,0,0,0,0,0
23979,23980,20000,1,2,2,23,2,0,0,2,...,0,0,1,0,0,0,0,0,0,0
23980,23981,50000,1,2,2,23,0,0,0,-1,...,0,0,1,0,0,0,0,0,0,0
23981,23982,20000,1,3,2,24,-1,2,-1,-1,...,0,1,0,0,0,0,0,0,0,0
23982,23983,130000,1,2,2,25,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
23983,23984,160000,1,2,2,25,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
23984,23985,110000,1,2,2,25,0,-1,0,0,...,0,1,0,0,0,0,0,0,0,0
23985,23986,50000,1,2,2,37,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
23986,23987,50000,1,2,2,25,0,0,4,3,...,0,0,0,1,0,0,0,0,0,0
23987,23988,240000,1,2,2,26,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
23988,23989,20000,1,2,2,27,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
23989,23990,500000,1,3,2,30,-1,0,0,0,...,0,1,0,0,0,0,0,0,0,0
23990,23991,60000,1,2,2,26,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
23991,23992,50000,1,3,2,25,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
23992,23993,50000,1,2,2,24,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
23993,23994,20000,1,2,2,25,-1,-1,-1,-1,...,0,0,1,0,0,0,0,0,0,0
23994,23995,30000,1,2,2,25,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
23995,23996,80000,1,2,1,25,1,2,2,0,...,0,0,1,0,0,0,0,0,0,0
23996,23997,20000,1,2,1,25,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
23997,23998,10000,1,2,2,26,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
23998,23999,20000,1,5,2,26,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
23999,24000,100000,1,1,2,26,0,-1,0,0,...,0,0,1,0,0,0,0,0,0,0

In [4]:
from sklearn.preprocessing import StandardScaler

bill = ['BILL_AMT1', 'BILL_AMT2', 'BILL_AMT3', 'BILL_AMT4', 'BILL_AMT5', 'BILL_AMT6']
bill_values = data.loc[:, bill].values
target_values = data.loc[:, ['default payment next month']].values
bill_values = StandardScaler().fit_transform(bill_values)
bill_values

array([[-0.64260509, -0.64727168, -0.66984012, -0.67177126, -0.66288023,
        -0.65191478],
       [-0.65954984, -0.66684158, -0.64061403, -0.61989188, -0.60562493,
        -0.59678798],
       [-0.29399193, -0.49200571, -0.48110963, -0.44454526, -0.41516611,
        -0.38906085],
       ...,
       [-0.57420665, -0.55018959, -0.5358664 , -0.39420387, -0.38765705,
        -0.49679563],
       [-0.41340357, -0.40308131, -0.39554301, -0.03834173, -0.66288023,
        -0.65191478],
       [-0.67521444, -0.67644889, -0.64963262, -0.64094806, -0.65643383,
        -0.63127392]])

In [5]:
from sklearn.decomposition import PCA

pca_bill = PCA(n_components=2)
principalComponents_bill = pca_bill.fit_transform(bill_values)
principalDf_bill = pd.DataFrame(data = principalComponents_bill
                                , columns = ['bill_pc1', 'bill_pc2'])
print(principalDf_bill)
pca_bill.explained_variance_ratio_

       bill_pc1  bill_pc2
0     -1.611216  0.010071
1     -1.546814 -0.066453
2     -1.028676  0.013599
3     -0.233383  0.177654
4     -0.960107 -0.227755
...         ...       ...
23995  1.058638  0.135535
23996 -1.031067 -0.121125
23997 -1.198402 -0.141770
23998 -1.043755  0.152590
23999 -1.604194 -0.037400

[24000 rows x 2 columns]

array([0.90774248, 0.04974495])

In [6]:
pay = ['PAY_AMT1','PAY_AMT2', 'PAY_AMT3', 'PAY_AMT4', 'PAY_AMT5', 'PAY_AMT6']
pay_values = data.loc[:, pay].values
pay_values = StandardScaler().fit_transform(pay_values)
pay_values

array([[-0.3678535 , -0.24649878, -0.30874059, -0.31871886, -0.31325859,
        -0.29435041],
       [-0.3678535 , -0.23154441, -0.24661057, -0.25152793, -0.31325859,
        -0.18090744],
       [-0.26711195, -0.20750202, -0.24661057, -0.25152793, -0.24777108,
        -0.01074299],
       ...,
       [-0.28157945, -0.17384267, -0.22797157, -0.29721776, -0.19407132,
        -0.23762892],
       [-0.16510948, -0.20908882, -0.24064609, -0.25152793, -0.31325859,
        -0.29435041],
       [-0.29485238, -0.22192745, -0.24661057, -0.28512339, -0.24777108,
        -0.23762892]])

In [7]:
pca_pay = PCA(n_components=6)
principalComponents_pay = pca_pay.fit_transform(pay_values)
principalDf_pay = pd.DataFrame(data = principalComponents_pay
                               , columns = ['pay_pc1', 'pay_pc2', 'pay_pc3', 'pay_pc4', 'pay_pc5', 'pay_pc6'])
print(principalDf_pay)
pca_pay.explained_variance_ratio_

        pay_pc1   pay_pc2   pay_pc3   pay_pc4   pay_pc5   pay_pc6
0     -0.753442  0.056474  0.016774  0.028364 -0.043054  0.062851
1     -0.650050 -0.004134 -0.014271  0.023947 -0.119676  0.078670
2     -0.500570  0.038109 -0.131170 -0.038420 -0.161752  0.055923
3     -0.560491  0.045290 -0.003965  0.025886  0.009334  0.045229
4      0.554640  0.219275  0.637498  0.538860  0.123918  1.227617
...         ...       ...       ...       ...       ...       ...
23995 -0.407177 -0.084874 -0.035315  0.049919  0.036277 -0.098074
23996 -0.581877  0.059387 -0.009436  0.068554 -0.010585  0.085266
23997 -0.573232  0.106235  0.023023  0.044355 -0.033970  0.020399
23998 -0.599453  0.009161 -0.046206  0.047729  0.102597  0.050621
23999 -0.624371  0.056763 -0.001320  0.031416 -0.038328  0.025310

[24000 rows x 6 columns]

array([0.30061902, 0.14779329, 0.14538284, 0.14006904, 0.13443381,
       0.131702  ])

### Above suggests 'amount of previous payment' cannot be reduced in dimensionality simply by PCA

In [8]:
data = pd.concat([data, principalDf_bill], axis = 1)
data = data.drop(bill, axis=1)
data.columns

Index(['ID', 'LIMIT_BAL', 'SEX', 'EDUCATION', 'MARRIAGE', 'AGE', 'PAY_0',
       'PAY_2', 'PAY_3', 'PAY_4', 'PAY_5', 'PAY_6', 'PAY_AMT1', 'PAY_AMT2',
       'PAY_AMT3', 'PAY_AMT4', 'PAY_AMT5', 'PAY_AMT6',
       'default payment next month', '['SEX']_1', '['SEX']_2',
       '['EDUCATION']_0', '['EDUCATION']_1', '['EDUCATION']_2',
       '['EDUCATION']_3', '['EDUCATION']_4', '['EDUCATION']_5',
       '['EDUCATION']_6', '['MARRIAGE']_0', '['MARRIAGE']_1', '['MARRIAGE']_2',
       '['MARRIAGE']_3', '['PAY_0']_-2', '['PAY_0']_-1', '['PAY_0']_0',
       '['PAY_0']_1', '['PAY_0']_2', '['PAY_0']_3', '['PAY_0']_4',
       '['PAY_0']_5', '['PAY_0']_6', '['PAY_0']_7', '['PAY_0']_8',
       '['PAY_2']_-2', '['PAY_2']_-1', '['PAY_2']_0', '['PAY_2']_1',
       '['PAY_2']_2', '['PAY_2']_3', '['PAY_2']_4', '['PAY_2']_5',
       '['PAY_2']_6', '['PAY_2']_7', '['PAY_2']_8', '['PAY_3']_-2',
       '['PAY_3']_-1', '['PAY_3']_0', '['PAY_3']_1', '['PAY_3']_2',
       '['PAY_3']_3', '['PAY_3']_4', '['PAY_3']_5', '['PAY_3']_6',
       '['PAY_3']_7', '['PAY_3']_8', '['PAY_4']_-2', '['PAY_4']_-1',
       '['PAY_4']_0', '['PAY_4']_1', '['PAY_4']_2', '['PAY_4']_3',
       '['PAY_4']_4', '['PAY_4']_5', '['PAY_4']_6', '['PAY_4']_7',
       '['PAY_4']_8', '['PAY_5']_-2', '['PAY_5']_-1', '['PAY_5']_0',
       '['PAY_5']_2', '['PAY_5']_3', '['PAY_5']_4', '['PAY_5']_5',
       '['PAY_5']_6', '['PAY_5']_7', '['PAY_5']_8', '['PAY_6']_-2',
       '['PAY_6']_-1', '['PAY_6']_0', '['PAY_6']_2', '['PAY_6']_3',
       '['PAY_6']_4', '['PAY_6']_5', '['PAY_6']_6', '['PAY_6']_7',
       '['PAY_6']_8', 'bill_pc1', 'bill_pc2'],
      dtype='object')

### Do a logistic regression to give a rough feature selection

In [9]:
covariates = list(data.columns)
covariates.remove('ID')
covariates.remove('default payment next month')

for element in categories:
    covariates.remove(element)

X_logit = data[covariates]
Y_logit = data['default payment next month']

In [10]:
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression

logreg = LogisticRegression(solver='lbfgs', max_iter=700)
rfe = RFE(logreg, 10)

rfe = rfe.fit(X_logit, Y_logit.values.ravel())
print(rfe.support_)
print(rfe.ranking_)

[False False False False False False False False False False False  True
  True  True False False False  True False False False False False False
 False  True  True  True False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False  True  True False False
 False  True False False False False False False False False False False
 False False False]
[56 49 50 51 52 53 55 54 40 30 67  1  1  1 13 14 46  1 22 23 21  3 15  2
 16  1  1  1 66 68 59 63 38  4 37 72 35 36 12  7 58 64 75 29 28 34 73  9
 11 32 57 61  8 76 33 48 42 71 20 41 10 60 78 27 77 47 31 45  1  1 17 65
 70  1 74 25 18 19 26  5 24 62  6 43 69 44 39]

In [11]:
X_logit = X_logit.iloc[:, list(rfe.support_)]
to_keep = data.loc[:, ['LIMIT_BAL', 'PAY_AMT1', 'PAY_AMT2', 'PAY_AMT3', 'PAY_AMT4', 'PAY_AMT5', 'PAY_AMT6', 
                        'bill_pc1', 'bill_pc2']]
X_logit = pd.concat((X_logit, to_keep), axis=1)

In [12]:
import statsmodels.api as sm

logit_model=sm.Logit(Y_logit,X_logit)
result=logit_model.fit()
print(result.summary2())

Optimization terminated successfully.
         Current function value: 0.459093
         Iterations 7
                              Results: Logit
===========================================================================
Model:              Logit                      Pseudo R-squared: 0.136
Dependent Variable: default payment next month AIC:              22074.4863
Date:               2019-12-17 14:46           BIC:              22228.1167
No. Observations:   24000                      Log-Likelihood:   -11018.
Df Model:           18                         LL-Null:          -12759.
Df Residuals:       23981                      LLR p-value:      0.0000
Converged:          1.0000                     Scale:            1.0000
No. Iterations:     7.0000
-----------------------------------------------------------------------------
                    Coef.    Std.Err.      z       P>|z|     [0.025    0.975]
-----------------------------------------------------------------------------
['EDUCATION']_1    -1.1697     0.0449   -26.0394   0.0000   -1.2578   -1.0817
['EDUCATION']_2    -1.2049     0.0358   -33.6368   0.0000   -1.2752   -1.1347
['EDUCATION']_3    -1.1998     0.0482   -24.9010   0.0000   -1.2942   -1.1053
['MARRIAGE']_0     -1.4064     0.6372    -2.2071   0.0273   -2.6553   -0.1575
['PAY_0']_2         1.9779     0.0527    37.4967   0.0000    1.8745    2.0813
['PAY_0']_3         2.1291     0.1520    14.0090   0.0000    1.8312    2.4270
['PAY_0']_4         1.6415     0.2738     5.9946   0.0000    1.1048    2.1782
['PAY_5']_2         0.8996     0.0537    16.7418   0.0000    0.7943    1.0049
['PAY_5']_3         1.2625     0.1958     6.4479   0.0000    0.8787    1.6463
['PAY_5']_7         1.0275     0.3977     2.5837   0.0098    0.2481    1.8069
LIMIT_BAL          -0.0000     0.0000    -9.5930   0.0000   -0.0000   -0.0000
PAY_AMT1           -0.0000     0.0000    -5.9898   0.0000   -0.0000   -0.0000
PAY_AMT2           -0.0000     0.0000    -4.8328   0.0000   -0.0000   -0.0000
PAY_AMT3           -0.0000     0.0000    -3.7910   0.0002   -0.0000   -0.0000
PAY_AMT4           -0.0000     0.0000    -2.0884   0.0368   -0.0000   -0.0000
PAY_AMT5           -0.0000     0.0000    -2.4166   0.0157   -0.0000   -0.0000
PAY_AMT6           -0.0000     0.0000    -2.8068   0.0050   -0.0000   -0.0000
bill_pc1            0.0279     0.0092     3.0438   0.0023    0.0099    0.0458
bill_pc2           -0.0953     0.0399    -2.3864   0.0170   -0.1736   -0.0170
===========================================================================

In [13]:
data.columns

Index(['ID', 'LIMIT_BAL', 'SEX', 'EDUCATION', 'MARRIAGE', 'AGE', 'PAY_0',
       'PAY_2', 'PAY_3', 'PAY_4', 'PAY_5', 'PAY_6', 'PAY_AMT1', 'PAY_AMT2',
       'PAY_AMT3', 'PAY_AMT4', 'PAY_AMT5', 'PAY_AMT6',
       'default payment next month', '['SEX']_1', '['SEX']_2',
       '['EDUCATION']_0', '['EDUCATION']_1', '['EDUCATION']_2',
       '['EDUCATION']_3', '['EDUCATION']_4', '['EDUCATION']_5',
       '['EDUCATION']_6', '['MARRIAGE']_0', '['MARRIAGE']_1', '['MARRIAGE']_2',
       '['MARRIAGE']_3', '['PAY_0']_-2', '['PAY_0']_-1', '['PAY_0']_0',
       '['PAY_0']_1', '['PAY_0']_2', '['PAY_0']_3', '['PAY_0']_4',
       '['PAY_0']_5', '['PAY_0']_6', '['PAY_0']_7', '['PAY_0']_8',
       '['PAY_2']_-2', '['PAY_2']_-1', '['PAY_2']_0', '['PAY_2']_1',
       '['PAY_2']_2', '['PAY_2']_3', '['PAY_2']_4', '['PAY_2']_5',
       '['PAY_2']_6', '['PAY_2']_7', '['PAY_2']_8', '['PAY_3']_-2',
       '['PAY_3']_-1', '['PAY_3']_0', '['PAY_3']_1', '['PAY_3']_2',
       '['PAY_3']_3', '['PAY_3']_4', '['PAY_3']_5', '['PAY_3']_6',
       '['PAY_3']_7', '['PAY_3']_8', '['PAY_4']_-2', '['PAY_4']_-1',
       '['PAY_4']_0', '['PAY_4']_1', '['PAY_4']_2', '['PAY_4']_3',
       '['PAY_4']_4', '['PAY_4']_5', '['PAY_4']_6', '['PAY_4']_7',
       '['PAY_4']_8', '['PAY_5']_-2', '['PAY_5']_-1', '['PAY_5']_0',
       '['PAY_5']_2', '['PAY_5']_3', '['PAY_5']_4', '['PAY_5']_5',
       '['PAY_5']_6', '['PAY_5']_7', '['PAY_5']_8', '['PAY_6']_-2',
       '['PAY_6']_-1', '['PAY_6']_0', '['PAY_6']_2', '['PAY_6']_3',
       '['PAY_6']_4', '['PAY_6']_5', '['PAY_6']_6', '['PAY_6']_7',
       '['PAY_6']_8', 'bill_pc1', 'bill_pc2'],
      dtype='object')